"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./src/components/layout/Sidebar";
import NavBar from "./src/components/layout/Navbar";
import { Poppins } from "next/font/google";
import { useState } from "react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // los pesos que necesites
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const [sidebarOpen, setSidebarOpen] = useState(true);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} antialiased flex bg-[#F5F5F5]`}
      >
        <main className="flex-1 bg-gray-100 min-h-screen">
          <div className="flex flex-row">
            <Sidebar open={sidebarOpen} />
            <div className="flex flex-col w-full gap-3">
              <NavBar toggleSidebar={() => setSidebarOpen(!sidebarOpen)} />
              <div className="p-5">{children}</div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
